name: falconx
description: A new Flutter package project.
version: 1.0.0

environment:
  sdk: '>=2.19.3 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  falmodel:
    git:
      url: https://github.com/THE-EXISTING/falmodel.git
      ref: develop
  faltool:
    git:
      url: https://github.com/THE-EXISTING/faltool.git
      ref: develop
  falconnect:
    git:
      url: https://github.com/THE-EXISTING/falconnect.git
      ref: develop
  falstore:
    git:
      url: https://github.com/THE-EXISTING/falstore.git
      ref: develop

  flutter_lints: ^2.0.2
  flutter_cache_manager: ^3.3.1
  flutter_local_notifications: ^15.0.0
  provider: ^6.0.5

  #=======  UI ========#
  webview_flutter: ^4.2.2
  shimmer_animation: ^2.1.0+1
  flutter_svg: ^2.0.7
#  fluttertoast: ^8.2.1
#  badges: ^3.1.1
#  wechat_assets_picker: ^8.4.2
#  progressive_image: ^2.0.1
#  mask_text_input_formatter: ^2.4.0
#  pin_code_fields: ^7.4.0
#  responsive_framework: ^1.0.0
#  drop_shadow: ^0.1.0
#  group_button: ^5.2.2
#  dropdown_button2: ^2.1.2
#  sms_autofill: ^2.3.0
#  qr_code_scanner: ^1.0.1
#  qr_flutter: ^4.1.0
#  loading_animation_widget: ^1.2.0+4
#  carousel_slider: ^4.2.1

  #======= Analytic ========#
  sentry_flutter: ^7.8.0

  #======= Utils ========#
  intl: ^0.18.1
  go_router: ^9.0.0
  flutter_bloc: ^8.1.3
  device_info_plus: ^9.0.2
  flutter_keyboard_visibility: ^5.4.1
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  image_network: ^2.5.4+1
  uni_links: ^0.5.1
  version: ^3.0.2
#  package_info_plus: ^4.0.2
#  catcher:
#    git:
#      url: https://github.com/THE-EXISTING/catcher.git
#      ref: master

#  url_launcher: ^6.1.11
#  sim_data: ^0.0.2
#  url_strategy: ^0.2.0
#  universal_io: ^2.2.0
#  share_plus: ^6.3.4
#  tap_debouncer: ^2.0.2
#  permission_handler: ^10.2.0
#  http_parser: ^4.0.2
#  path_provider: ^2.0.15
#  timer_count_down: ^2.2.2
#  screen_brightness: ^0.2.2
#  wakelock: ^0.6.2
#  flutter_libphonenumber: ^2.1.3
#  open_file: ^3.3.1
#  universal_html: ^2.2.1
#  android_intent_plus: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
