name: falconx
description: A new Flutter package project.
version: 1.0.2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  faltool:
    git:
      url: https://github.com/THE-EXISTING/faltool.git
      ref: 1.0.2
  falkit:
    git:
      url: https://github.com/THE-EXISTING/falkit.git
      ref: 1.0.1
  falmodel:
    git:
      url: https://github.com/THE-EXISTING/falmodel.git
      ref: 1.0.2
  falconnect:
#    path: ../falconnect
    git:
      url: https://github.com/THE-EXISTING/falconnect.git
      ref: 1.0.2
  falstore:
    git:
      url: https://github.com/THE-EXISTING/falstore.git
      ref: 1.0.2

  #PLATFORM: All
  provider: ^6.1.2
  #PLATFORM: Android, iOS, Linux, MacOS
  flutter_local_notifications: ^17.1.2

  #=======  UI ========#
  #PLATFORM: Android, iOS
  webview_flutter: ^4.7.0

  #======= Utils ========#
  #PLATFORM: All
  go_router: ^14.1.1
  flutter_bloc: ^8.1.5
  #PLATFORM: Android, iOS, Web
  uni_links: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
