name: falconx
description: A new Flutter package project.
version: 1.0.0

environment:
  sdk: '>=2.19.3 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  falmodel:
    path: ../falmodel
  faltool:
    path: ../faltool
  falconnect:
    path: ../falconnect
  falstore:
    path: ../falstore

  flutter_lints: ^2.0.1
  webview_flutter: ^3.0.4
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^14.0.0+1
  provider: ^6.0.5

  #=======  UI ========#
  shimmer_animation: ^2.1.0+1
  badges: ^3.1.1
  wechat_assets_picker: ^8.4.2
  fluttertoast: ^8.2.1
  progressive_image: ^2.0.1
  flutter_svg: ^2.0.5
  mask_text_input_formatter: ^2.4.0
  pin_code_fields: ^7.4.0
  responsive_framework: ^1.0.0
  drop_shadow: ^0.1.0
  group_button: ^5.2.2
  dropdown_button2: ^2.1.0
  country_code_picker: ^3.0.0
  sms_autofill: ^2.3.0
  qr_code_scanner: ^1.0.1
  loading_animation_widget: ^1.2.0+4

  #======= Analytic ========#
  sentry_flutter: ^7.5.2

  #======= Utils ========#
  #  catcher: any #conflict with device_info_plus and conflict with dio
  catcher:
    git:
      url: https://github.com/THE-EXISTING/catcher.git
      ref: master

  intl: ^0.17.0
  sim_data: ^0.0.2
  go_router: ^6.5.8
  url_strategy: ^0.2.0
  universal_io: ^2.2.0
  flutter_bloc: ^8.1.2
  share_plus: ^6.3.4
  device_info_plus: ^8.2.2
  package_info_plus: ^3.1.2
  flutter_keyboard_visibility: ^5.4.1
  tap_debouncer: ^2.0.2
  permission_handler: ^10.2.0
  equatable: ^2.0.5
  url_launcher: ^6.1.11
  cached_network_image: ^3.2.3
  image_network: ^2.5.2
  http_parser: ^4.0.2
  path_provider: ^2.0.15
  uni_links: ^0.5.1
  flutter_multi_formatter: ^2.11.0
  qr_flutter: ^4.0.0
  timer_count_down: ^2.2.2
  version: ^3.0.2
  screen_brightness: ^0.2.2
  wakelock: ^0.6.2
  flutter_libphonenumber: ^2.1.2
  open_file: ^3.3.1
  universal_html: ^2.2.1
  android_intent_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
