name: falconx
description: A new Flutter package project.
version: 1.0.0

environment:
  sdk: '>=2.19.3 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  falmodel:
    git:
      url: https://github.com/THE-EXISTING/falmodel.git
      ref: develop
  faltool:
    git:
      url: https://github.com/THE-EXISTING/faltool.git
      ref: develop
  falconnect:
    git:
      url: https://github.com/THE-EXISTING/falconnect.git
      ref: develop
  falstore:
    git:
      url: https://github.com/THE-EXISTING/falstore.git
      ref: develop

  flutter_lints: ^2.0.2
  flutter_cache_manager: ^3.3.1
  flutter_local_notifications: ^15.0.0
  provider: ^6.0.5

  #=======  UI ========#
  webview_flutter: ^4.2.2
  shimmer_animation: ^2.1.0+1
  flutter_svg: ^2.0.7
#  progressive_image: ^2.0.1
#  mask_text_input_formatter: ^2.4.0
#  pin_code_fields: ^7.4.0
#  drop_shadow: ^0.1.0
#  sms_autofill: ^2.3.0

  #======= Analytic ========#
  sentry_flutter: ^7.8.0

  #======= Utils ========#
  intl: ^0.18.1
  go_router: ^9.0.0
  flutter_bloc: ^8.1.3
  device_info_plus: ^9.0.2
  flutter_keyboard_visibility: ^5.4.1
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  image_network: ^2.5.4+1
  uni_links: ^0.5.1
  version: ^3.0.2
  package_info_plus: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
