name: falconx
description: A new Flutter package project.
version: 1.4.7

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  faltool:
    git:
      url: https://github.com/THE-EXISTING/faltool.git
      ref: 1.0.11
  falkit:
    git:
      url: https://github.com/THE-EXISTING/falkit.git
      ref: 1.1.4
  falmodel:
    git:
      url: https://github.com/THE-EXISTING/falmodel.git
      ref: 1.2.5
  falconnect:
    git:
      url: https://github.com/THE-EXISTING/falconnect.git
      ref: 1.2.8
  falstore:
    git:
      url: https://github.com/THE-EXISTING/falstore.git
      ref: 1.1.8

  #PLATFORM: All
  provider: ^6.1.2

  #PLATFORM: Android, iOS, Linux, MacOS
  flutter_local_notifications: ^17.2.4

  #======= Utils ========#
  #PLATFORM: All
  go_router: ^14.3.0
  flutter_bloc: ^8.1.6
  #PLATFORM: Android, iOS, Web
  uni_links: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
