name: falconx
description: A new Flutter package project.
version: 1.0.0

environment:
  sdk: '>=2.19.3 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  falmodel:
    git:
      url: https://github.com/THE-EXISTING/falmodel.git
      ref: develop
  faltool:
    git:
      url: https://github.com/THE-EXISTING/faltool.git
      ref: develop
  falconnect:
#    path: ../falconnect
    git:
      url: https://github.com/THE-EXISTING/falconnect.git
      ref: develop
  falstore:
    git:
      url: https://github.com/THE-EXISTING/falstore.git
      ref: develop

  #PLATFORM: All
  provider: ^6.1.1
  #PLATFORM: Android, iOS, Linux, MacOS
  flutter_local_notifications: ^16.1.0
  #PLATFORM: Android, iOS, MacOS
  flutter_cache_manager: ^3.3.1

  #=======  UI ========#
  #PLATFORM: All
  flutter_svg: ^2.0.9
  shimmer_animation: ^2.1.0+1
  #PLATFORM: Android, iOS
  webview_flutter: ^4.4.2

  #======= Utils ========#
  #PLATFORM: All
  intl: ^0.18.1
  go_router: ^12.1.1
  flutter_bloc: ^8.1.3
  device_info_plus: ^9.1.0
  flutter_keyboard_visibility: ^5.4.1
  equatable: ^2.0.5
  version: ^3.0.2
  package_info_plus: ^4.2.0
  image_network: ^2.5.4+1
  #PLATFORM: Android, iOS, MacOS
  cached_network_image: ^3.3.0
  #PLATFORM: Android, iOS, Web
  uni_links: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


dependency_overrides:
  uuid: ^4.2.1

flutter:
